### ISSUE TITLE
Autoloading

### ISSUE THREAD

**Issue by shiki** [firephp/firephp#1]
Hi,

I once made a [Yii Framework extension](http://www.yiiframework.com/extension/firephp-logroute) for the old FirePHPCore library 0.3.2. 

I'm now trying to update that to use FirePHP 1.0. I am currently having problems with the autoload function in `FirePHP/Init.php` named `FirePHP__autoload`. I wish there was an easy way to _register_ it before `FirePHP__main()` is called. The reason is when I include `FirePHP/Init.php`, `FirePHP__main()` is automatically called and registers `FirePHP__autoload`. This autoloader will be put on second priority before Yii's own autoloader and hence I will get this error:

```
include(Insight_Util.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory 
```

I wish there was a way to rearrange the autoloaders so I can put `FirePHP__autoload` first before Yii's autoloader. This will definitely prevent this error from happening.

**Comment by cadorn** [comment]
@shiki Did the PR fix your issue?
