### ISSUE TITLE
Firebug lost log

### ISSUE THREAD

**Issue by daddykom** [firephp/firephp#15]
Hi all

I did not found any solution in the net and could not understand how to solve this:

If i us fb() to show variables, it gives no output if i call fb more than 100 times.
response header stops with x-wf-1-1-1-99
Headers in attachment..

where is the problem her? 
- is it a bug?
- is it a limit? from firephp? from firebug? from apache?

If it is from firephp, how i can change it?

Greetings
Charley

[log.txt](https://github.com/firephp/firephp/files/576106/log.txt)

**Comment by cadorn** [comment]
Apache and browsers limit size of headers.
